# Development Environment Configuration
name: development
description: "開發環境 - 用於日常開發和功能測試"

# GitHub Environment Protection Rules
protection_rules:
  required_reviewers: 0
  wait_timer: 0
  prevent_self_review: false

# Environment Variables
variables:
  ENVIRONMENT: "development"
  LOG_LEVEL: "DEBUG"
  DEBUG: "true"
  CONTAINER_REGISTRY: "ghcr.io"
  DEPLOY_NAMESPACE: "discord-bot-dev"
  
  # Resource Limits
  MEMORY_LIMIT: "512Mi"
  CPU_LIMIT: "0.5"
  REPLICA_COUNT: "1"
  
  # Monitoring Settings
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30s"
  HEALTH_CHECK_TIMEOUT: "10s"
  
  # Feature Flags
  ACTIVITY_METER_ENABLED: "true"
  MESSAGE_LISTENER_ENABLED: "true"
  PROTECTION_ENABLED: "false"  # Disable in dev to avoid false alerts
  WELCOME_ENABLED: "true"
  SYNC_DATA_ENABLED: "true"

# Secrets (these should be configured in GitHub repository settings)
secrets:
  - DISCORD_TOKEN_DEV
  - DATABASE_ENCRYPTION_KEY_DEV
  - WEBHOOK_URL_DEV

# Deployment Strategy
deployment:
  strategy: "recreate"  # Simple strategy for development
  max_unavailable: "100%"
  max_surge: "0%"
  
  # Health Checks
  readiness_probe:
    path: "/health"
    port: 8080
    initial_delay: 30
    period: 10
    timeout: 5
    failure_threshold: 3
  
  liveness_probe:
    path: "/health"
    port: 8080
    initial_delay: 60
    period: 30
    timeout: 10
    failure_threshold: 3

# Database Configuration
database:
  backup_enabled: false
  wal_mode: true
  query_timeout: 30
  connection_pool_size: 5

# Logging Configuration
logging:
  level: "DEBUG"
  format: "json"
  file_retention_days: 7
  max_file_size: "10MB"