"""成就系統常數定義."""

# 數值限制
ACHIEVEMENT_NAME_MAX_LENGTH = 100
ACHIEVEMENT_DESCRIPTION_MAX_LENGTH = 500
ACHIEVEMENT_POINTS_MAX = 10000
ACHIEVEMENT_ROLE_REWARD_MAX_LENGTH = 100
CATEGORY_NAME_MAX_LENGTH = 50
CATEGORY_DESCRIPTION_MAX_LENGTH = 200
CATEGORY_ICON_MAX_LENGTH = 10

# ============= 時間相關(秒) =============
HOUR_IN_SECONDS = 3600
NON_WORK_HOURS_START = 22
NON_WORK_HOURS_END = 6

# 快取相關
CACHE_KEY_MAX_LENGTH = 500
CACHE_INVALIDATION_BUFFER_SIZE = 100
MINIMUM_CACHE_PARTS = 2

# 效能相關
MIN_HIT_RATE_THRESHOLD = 50
HIGH_HIT_RATE_THRESHOLD = 90
MIN_REQUEST_COUNT_FOR_ADJUSTMENT = 100
HIGH_REQUEST_COUNT_THRESHOLD = 1000
CRITICAL_USAGE_RATE = 95
WARNING_USAGE_RATE = 80
LOW_USAGE_RATE = 30
MINIMUM_CACHE_SIZE = 100
CACHE_SIZE_REDUCTION_THRESHOLD = 30

# 快取效率閾值
EXCELLENT_HIT_RATE = 80
GOOD_HIT_RATE = 60
FAIR_HIT_RATE = 40
POOR_HIT_RATE = 20

# 安全相關
MAX_FAILED_OPERATIONS = 10
HIGH_PRIORITY_THRESHOLD = 5

# 查詢和處理限制
MAX_FIELD_CHANGES_DISPLAY = 3
MAX_SNAPSHOTS_HISTORY = 100
MAX_SNAPSHOTS_KEEP = 50
MAX_LEAK_RECORDS = 50
MAX_LEAK_RECORDS_KEEP = 25
MIN_SNAPSHOTS_FOR_TREND = 10
MIN_SNAPSHOTS_FOR_COMPARISON = 2

# ============= 記憶體相關(MB) =============
MEMORY_LEAK_THRESHOLD_MB = 1.0
HIGH_MEMORY_USAGE_MB = 10
MEMORY_CRITICAL_THRESHOLD_MB = 100
MEMORY_WARNING_THRESHOLD_MB = 80
MEMORY_INFO_THRESHOLD_MB = 50

# ============= 效能分析閾值(毫秒) =============
SLOW_QUERY_THRESHOLD_MS = 200
CRITICAL_RESPONSE_TIME_MS = 500
HIGH_RESPONSE_TIME_MS = 300
EXCELLENT_RESPONSE_TIME_MS = 100
GOOD_RESPONSE_TIME_MS = 200
FAIR_RESPONSE_TIME_MS = 300
POOR_RESPONSE_TIME_MS = 500

# 效能比率閾值
EXCELLENT_SLOW_QUERY_RATIO = 0.1
GOOD_SLOW_QUERY_RATIO = 0.2
FAIR_SLOW_QUERY_RATIO = 0.3
POOR_SLOW_QUERY_RATIO = 0.5
HIGH_EFFICIENCY_THRESHOLD = 0.1
LOW_HIT_RATE_THRESHOLD = 0.6
HIGH_SLOW_QUERY_RATIO = 0.2

# 批次處理
MIN_BATCH_SIZE = 10
DEFAULT_BATCH_SIZE = 50
MAX_BATCH_USERS = 50

# 測試相關
MIN_SUCCESS_RATE = 0.95
HIGH_P95_THRESHOLD_MS = 500

# 儀表板相關
DASHBOARD_METRICS_HISTORY = 30
DASHBOARD_BREAKDOWN_HISTORY = 10

# 快取清理
MAX_CACHE_ITEMS = 10000

# ============= 參數位置索引(用於快取策略) =============
ARG_INDEX_2 = 2
ARG_INDEX_3 = 3
ARG_INDEX_4 = 4
ARG_INDEX_5 = 5
