"""
歡迎系統配置模組初始化檔案
"""

from .config import (
    DEFAULT_SETTINGS,
    DEFAULT_BG_SIZE,
    DEFAULT_BG_COLOR,
    DEFAULT_TEXT_COLOR,
    DEFAULT_AVATAR_SIZE,
    DEFAULT_FONT_PATH,
    CACHE_TIMEOUT,
    MAX_CACHE_SIZE,
    LOG_FORMAT,
    LOG_MAX_SIZE,
    LOG_BACKUP_COUNT
) 