"""訊息監聽器常數定義."""

# 訊息內容顯示限制
MESSAGE_CONTENT_MAX_DISPLAY = 100
MESSAGE_CONTENT_TRUNCATE_SUFFIX = "..."
MESSAGE_CONTENT_PREVIEW_MAX = 97

# 結果顯示限制
MAX_RECENT_MESSAGES_DISPLAY = 5

# 預覽相關
PREVIEW_TEXT_MAX_LENGTH = 100
